# Generated by Django 5.2.16 on 2026-10-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
